console.log("임의의 숫자 생성하는 프로그램");
var n = Math.floor(Math.random() * 5) * 2 + 1;
console.log("생성한 숫자는 " + n + "입니다.");
n = Math.floor(Math.random() * 5) * 2 + 1;
console.log("생성한 숫자는 " + n + "입니다.");
n = Math.floor(Math.random() * 5) * 2 + 1;
console.log("생성한 숫자는 " + n + "입니다.");
n = Math.floor(Math.random() * 5) * 2 + 1;
console.log("생성한 숫자는 " + n + "입니다.");
n = Math.floor(Math.random() * 5) * 2 + 1;
console.log("생성한 숫자는 " + n + "입니다.");
console.log("끝");
